# fly.toml app configuration file generated for fodinha-api on 2026-07-04T19:14:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fodinha-api'
primary_region = 'gru'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[deploy]
  strategy = 'rolling'

[build]

[env]
  google_client_id = "112306439846-2ivn23do1uh156v0lpjtu22gu8f98sd4.apps.googleusercontent.com"
  object_storage_bucket = "fodinha-bucket"
  object_storage_access_key_id = "tid_biVsgUMgEBzotVCayyVnLWSZCznEXejwJiUhrvSJvCMBRSbVGX"
  object_storage_endpoint = "https://t3.storage.dev"
  object_storage_force_path_style = false
  object_storage_region = "auto"
  object_storage_public_base_url = "https://fodinha-bucket.t3.tigrisbucket.io"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '3s'
    interval = '1s'
    method = 'GET'
    path = '/readyz'
    timeout = '1s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[metrics]]
  port = 3000
  path = '/metrics'
