# fly.toml app configuration file generated for fodinha-api on 2026-07-04T19:14:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fodinha-api'
primary_region = 'gru'

[build]

[env]
  google_client_id = 112306439846-2ivn23do1uh156v0lpjtu22gu8f98sd4.apps.googleusercontent.com

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[metrics]]
  port = 3000
  path = '/metrics'
